# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Menu' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'SwiftMessages'
pod 'Toast-Swift', '~> 5.0.0'
pod 'Alamofire', '~> 4.7'
pod 'Kingfisher'
pod 'SDWebImage/WebP'
pod 'IQKeyboardManagerSwift'
pod 'NVActivityIndicatorView'
pod 'IBAnimatable'
  # Pods for Menu

end
